language: node_js
node_js:
- '12'
- '14'
services:
- redis-server
script:
- echo 'Starting'
- npm install
- echo 'Testing'
- npm test
deploy:
  provider: heroku
  api_key:
    secure: bac531a4-4119-4510-8653-551f822b57cd
  app: devops_amine_webapp
  on:
    repo: AmineTs/DevOps_CRUD_project
    branch: main
  skip_cleanup: 'true'