apiVersion: apps/v1
kind: Deployment
metadata:
  name: amine-webapp-deployment
spec:
  selector:
    matchLabels:
      app: amine-webapp-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: amine-webapp-deployment
    spec:
      containers:
      - name: redis-server
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      
      - name: webapp
        image: fuzzer/ece_devops_webapp:latest
        ports:
        - containerPort: 3000
        

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-data-claim
         
        