---
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Install apt-transport-https"
  apt:
    name: apt-transport-https
    state: present



- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Install npm"
  apt:
    update_cache: yes
    name: npm
    state: present


- name: "Install Redis"
  apt: 
    update_cache: yes
    name: redis-server
    state: latest


- file: 
    path: "{{ appDir }}"
    mode: 0777
    recurse: yes 
    state: directory
    
   
- name: Building
  command: npm run 

- name: Running NPM install
  command: "npm install"
  args:
    chdir: "{{ appDir }}"
  register: npm_finished

- name: "Install forever (to run Amine's webapp)."
  npm: name=forever global=yes state=present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start Amine's webapp"
  command: forever start /vagrant
  when: "forever_list.stdout.find('/vagrant') == -1"