# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 # Sync webbapp folder

  config.vm.synced_folder "../", "/vagrant",
        mount_options: ["dmode=777,fmode=664"]


  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the VM
  config.vm.define "amine_server" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "kalilinux/rolling"
    # Specify the VM ip address
    server.vm.network :private_network, ip: "20.20.20.2"
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "kalilinux.server.local"
      # VM RAM in MB
      vb.memory = 2048
      # VM CPUs
      vb.cpus = 1
    end
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048"
      vmware.vmx["numvcpus"] = "1"
    end
  end
  

 # Use Vagrant Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "iac/playbooks/run.yml"
   
  end

  # Start provisioning
  $script = <<-SCRIPT
  echo I am provisionned !
  SCRIPT

  config.vm.provision "shell", inline: $script

end